version: '2'

services:
  # @see https://github.com/blacklabelops/jenkins/blob/master/docker-compose.yml
  jenkins:
    container_name: jenkins
    image: blacklabelops/jenkins
    hostname: localhost
    ports:
      - "8090:8080"
    volumes:
      - jenkinsdata:/jenkins
      - jenkinslogs:/var/log
    networks:
      - jenkinsnet
 
volumes:
  jenkinsdata:
    external: false
  jenkinslogs:
    external: false

networks:
  jenkinsnet:
    driver: bridge
